package phaseops

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/mihakrumpestar/panix/internal/phase"
	"github.com/mihakrumpestar/panix/internal/testutil"
	"github.com/rs/zerolog/log"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// validHardwareConfigOutput mirrors nixos-generate-config
// --show-hardware-config output, including its single trailing newline.
const validHardwareConfigOutput = `# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
`

// truncatedHardwareConfigOutput is a valid config cut off before the
// closing brace (the PTY can drop the last line of a captured stream).
const truncatedHardwareConfigOutput = `# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];
`

type hardwareConfigWriteCase struct {
	name        string
	output      string
	wantErr     string
	wantContent string
}

var hardwareConfigWriteCases = []hardwareConfigWriteCase{
	{
		name:        "valid config is written",
		output:      validHardwareConfigOutput,
		wantContent: validHardwareConfigOutput,
	},
	{
		name:    "empty output",
		output:  "",
		wantErr: "produced no output",
	},
	{
		name:    "stderr warning before the config",
		output:  "warning: Git tree '/repo' is dirty\n" + validHardwareConfigOutput,
		wantErr: "unexpected nixos-generate-config output",
	},
	{
		name:    "truncated config",
		output:  truncatedHardwareConfigOutput,
		wantErr: "truncated nixos-generate-config output",
	},
}

// stubNixosGenerateConfig writes a fake nixos-generate-config into a fresh temp
// dir and returns the dir to prepend to PATH, so no NixOS machine is needed.
func stubNixosGenerateConfig(t *testing.T, output string) string {
	t.Helper()

	dir := t.TempDir()
	outputPath := filepath.Join(dir, "output.txt")
	require.NoError(t, os.WriteFile(outputPath, []byte(output), 0o600))

	script := "#!/bin/sh\ncat " + outputPath + "\n"
	stubPath := filepath.Join(dir, "nixos-generate-config")
	//nolint:gosec // the stub must be executable to be found on PATH
	require.NoError(t, os.WriteFile(stubPath, []byte(script), 0o700))

	return dir
}

// TestGenerateHardwareConfig_Argv pins the argv: the show-hardware-config flags
// elevated via MaybeSudo; the output path is local and never part of the command.
func TestGenerateHardwareConfig_Argv(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		isRoot bool
		want   string
	}{
		{
			name:   "non-root: elevated",
			isRoot: false,
			want:   "sudo nixos-generate-config --show-hardware-config --no-filesystems",
		},
		{
			name:   "root: bare",
			isRoot: true,
			want:   "nixos-generate-config --show-hardware-config --no-filesystems",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			mach := newLocalTransferMachine(t, tt.isRoot)
			mach.HardwareConfigPath = "/tmp/hardware-configuration.nix"
			exc, phaseLog := testutil.NewDryRunExecutioner(t, mach, phase.Inspect)

			require.NoError(t, GenerateHardwareConfig(exc, mach))

			assert.Equal(t, tt.want, testutil.LastCommandLine(t, phaseLog))
		})
	}
}

// TestGenerateHardwareConfig_LocalWrite pins that captured stdout lands at the
// configured LOCAL path, including a nested directory whose name has spaces, and
// that the written file is staged so a git-backed flake sees it.
func TestGenerateHardwareConfig_LocalWrite(t *testing.T) {
	stubDir := stubNixosGenerateConfig(t, validHardwareConfigOutput)
	// Not parallel: t.Setenv forbids parallel tests.
	t.Setenv("PATH", stubDir+string(os.PathListSeparator)+os.Getenv("PATH"))

	repo := initTestRepo(t)
	path := filepath.Join(repo, "my hardware", "nix", "hardware-configuration.nix")
	mach := newLocalTransferMachine(t, true)
	mach.HardwareConfigPath = path

	exc, _ := realExecutionerFor(t, mach)

	require.NoError(t, GenerateHardwareConfig(exc, mach))

	content, err := os.ReadFile(path) //nolint:gosec // test-controlled temp path
	require.NoError(t, err)
	assert.Equal(t, validHardwareConfigOutput, string(content))

	gitInTestRepo(t, repo, "ls-files", "--error-unmatch", "my hardware/nix/hardware-configuration.nix")
}

// TestGenerateHardwareConfig_DryRunNoWrite pins that dry-run records the command
// but writes nothing.
func TestGenerateHardwareConfig_DryRunNoWrite(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "nested", "hardware-configuration.nix")
	mach := newLocalTransferMachine(t, false)
	mach.HardwareConfigPath = path
	exc, phaseLog := testutil.NewDryRunExecutioner(t, mach, phase.Inspect)

	require.NoError(t, GenerateHardwareConfig(exc, mach))

	assert.Equal(t, "sudo nixos-generate-config --show-hardware-config --no-filesystems", testutil.LastCommandLine(t, phaseLog))
	assert.NoFileExists(t, path)
}

func TestGenerateHardwareConfig_NoPathNoop(t *testing.T) {
	t.Parallel()

	mach := newLocalTransferMachine(t, false)
	exc, phaseLog := testutil.NewDryRunExecutioner(t, mach, phase.Inspect)

	require.NoError(t, GenerateHardwareConfig(exc, mach))

	assert.Empty(t, testutil.CommandLines(t, phaseLog))
}

// TestWriteHardwareConfig pins that only a recognized nixos-generate-config
// result is written; any other captured stream fails without leaving a file.
func TestWriteHardwareConfig(t *testing.T) {
	t.Parallel()

	for _, tt := range hardwareConfigWriteCases {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			runHardwareConfigWriteCase(t, tt)
		})
	}
}

func runHardwareConfigWriteCase(t *testing.T, tt hardwareConfigWriteCase) {
	t.Helper()

	path := filepath.Join(t.TempDir(), "nested", "hardware-configuration.nix")

	err := writeHardwareConfig(path, tt.output)
	if tt.wantErr != "" {
		require.Error(t, err)
		assert.Contains(t, err.Error(), tt.wantErr)
		assert.NoFileExists(t, path)

		return
	}

	require.NoError(t, err)

	content, err := os.ReadFile(path) //nolint:gosec // test-controlled temp path
	require.NoError(t, err)
	assert.Equal(t, tt.wantContent, string(content))
}

// initTestRepo creates a git repository in a fresh temp dir.
func initTestRepo(t *testing.T) string {
	t.Helper()

	repo := t.TempDir()
	gitInTestRepo(t, repo, "init", "-q")

	return repo
}

// gitInTestRepo runs git in dir with identity and signing pinned, since this
// environment's default git config demands signing; output is returned.
func gitInTestRepo(t *testing.T, dir string, args ...string) string {
	t.Helper()

	out, err := execGitIn(t, dir, args...)
	require.NoError(t, err, out)

	return out
}

// execGitIn runs git in dir like gitInTestRepo but returns the error so callers
// can assert failures.
func execGitIn(t *testing.T, dir string, args ...string) (string, error) {
	t.Helper()

	gitArgs := append([]string{"-C", dir, "-c", "commit.gpgsign=false", "-c", "user.email=t@t", "-c", "user.name=t"}, args...)

	//nolint:gosec // test-controlled arguments
	out, err := exec.CommandContext(context.Background(), "git", gitArgs...).CombinedOutput()

	return string(out), err
}

// TestStageHardwareConfig pins the staging matrix: an untracked file becomes
// git-visible, a gitignored file is force-staged, and a tracked file's index
// entry stays untouched.
func TestStageHardwareConfig(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		gitignored bool
		tracked    bool
	}{
		{name: "untracked file is staged"},
		{name: "gitignored file is force-staged", gitignored: true},
		{name: "tracked and modified file stays a no-op", tracked: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			runStageHardwareConfigCase(t, tt.gitignored, tt.tracked)
		})
	}
}

func runStageHardwareConfigCase(t *testing.T, gitignored, tracked bool) {
	t.Helper()

	repo := initTestRepo(t)

	if gitignored {
		require.NoError(t, os.WriteFile(filepath.Join(repo, ".gitignore"), []byte("hardware-configuration.nix\n"), 0o600))
	}

	path := filepath.Join(repo, "hardware-configuration.nix")
	require.NoError(t, os.WriteFile(path, []byte("original\n"), 0o600))

	if tracked {
		gitInTestRepo(t, repo, "add", "hardware-configuration.nix")
		require.NoError(t, os.WriteFile(path, []byte("modified\n"), 0o600))

		indexBefore := gitInTestRepo(t, repo, "ls-files", "-s", "hardware-configuration.nix")

		stageHardwareConfig(path)

		// A tracked path is already in the index: neither -N nor -fN may change it.
		assert.Equal(t, indexBefore, gitInTestRepo(t, repo, "ls-files", "-s", "hardware-configuration.nix"))

		return
	}

	stageHardwareConfig(path)

	// --error-unmatch exits non-zero unless the path is in the index; for the
	// gitignored case this proves the force retry ran.
	gitInTestRepo(t, repo, "ls-files", "--error-unmatch", "hardware-configuration.nix")
}

// TestStageHardwareConfig_NotARepo pins that a directory outside any git work
// tree is a silent no-op: the call completes and creates nothing.
func TestStageHardwareConfig_NotARepo(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "hardware-configuration.nix")
	require.NoError(t, os.WriteFile(path, []byte("modulesPath config, }\n"), 0o600))

	stageHardwareConfig(path)

	assert.NoFileExists(t, filepath.Join(dir, ".git"))
}

// TestStageHardwareConfig_GitUnavailable pins that a missing git binary is
// silent too: best-effort staging must not fail the deploy. Not parallel:
// t.Setenv forbids it.
func TestStageHardwareConfig_GitUnavailable(t *testing.T) {
	t.Setenv("PATH", t.TempDir())

	dir := t.TempDir()
	path := filepath.Join(dir, "hardware-configuration.nix")
	require.NoError(t, os.WriteFile(path, []byte("modulesPath config, }\n"), 0o600))

	stageHardwareConfig(path)

	assert.NoFileExists(t, filepath.Join(dir, ".git"))
}

// TestStageHardwareConfig_FailureWarns pins the last resort: when both add
// attempts fail (a locked index here) nothing is staged and the WARN names the
// manual command. Not parallel: it swaps the global logger.
//
//nolint:paralleltest // swaps the global logger to capture the WARN
func TestStageHardwareConfig_FailureWarns(t *testing.T) {
	repo := initTestRepo(t)
	path := filepath.Join(repo, "hardware-configuration.nix")
	require.NoError(t, os.WriteFile(path, []byte("modulesPath config, }\n"), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(repo, ".git", "index.lock"), nil, 0o600))

	logged := &bytes.Buffer{}
	previous := log.Logger
	log.Logger = log.Output(logged)

	t.Cleanup(func() { log.Logger = previous })

	stageHardwareConfig(path)

	assert.Contains(t, logged.String(), "could not stage the hardware config, run git -C")

	_, err := execGitIn(t, repo, "ls-files", "--error-unmatch", "hardware-configuration.nix")
	assert.Error(t, err, "nothing may be staged when both add attempts fail")
}
