# Note: you have to update this version to keep up
# https://github.com/golangci/golangci-lint/releases
version: v2.11.4

name: custom-gcl

destination: .devbox/bin

plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: latest
