version: "2"

issues:
  max-issues-per-linter: 1000
  max-same-issues: 100

linters:
  default: all

  disable:
    - tagliatelle # Bad check
    - tagalign # Bad check
    - ireturn # A lot of bubbletea is based on interfaces
    - goconst # Just some same strings across codebase
    - gochecknoglobals # constants are ok
    - forbidigo # We don't use print statements for debugging

  enable:
    - nilaway

  settings:
    lll:
      line-length: 150

    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-names:
        - ok

    revive:
      rules:
        - name: exported
          disabled: true

    staticcheck:
      checks:
        - all
        - -QF1008 # could remove embedded field from selector
        - -ST1000 # at least one file in a package should have a package comment

    custom:
      nilaway:
        type: module
        description: Static analysis tool to detect potential nil panics in Go code.
        settings:
          # Settings must be a "map from string to string" to mimic command line flags: the keys are
          # flag names and the values are the values to the particular flags.
          #include-pkgs: "<YOUR_PACKAGE_PREFIXES>"
          exclude-pkgs: "" # Exclude generated code
