version: "2"

linters:
  default: all
  exclusions:
    warn-unused: true

  disable:
    - tagliatelle # Bad check
    - tagalign # Bad check
    - ireturn # A lot of bubbletea is based on interfaces
    - goconst # Just some same strings across codebase
    - gochecknoglobals # Constants are ok
    - forbidigo # We don't use print statements for debugging
    - exhaustruct # Structs are generally initialized empty
    - exhaustive # Not necessery as we use default
    - containedctx # We use ctx to check if it is done
    - testpackage # Don't want separate packages for testing
    - wsl # Replaced by wsl_v5
    - prealloc # Usually we don't preallocate slices

  settings:
    govet:
      enable:
        - shadow
        - atomicalign
        - deepequalerrors
        #- fieldalignment # struct with 24 pointer bytes could be 16
        - nilness
        - reflectvaluecompare
      settings:
        shadow:
          strict: true

    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: errors
              desc: use github.com/pkg/errors instead

    lll:
      line-length: 150

    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-names:
        - ok
        - tt
        - fk
        - is
        - mu

    revive:
      rules:
        - name: exported
          disabled: true

    staticcheck:
      checks:
        - all
        - -QF1008 # could remove embedded field from selector
        - -ST1000 # at least one file in a package should have a package comment
        - -ST1003 # should not use underscores in package names 
    #unused:
    #  field-writes-are-uses: false
    #  post-statements-are-reads: true
    #  exported-fields-are-used: false
    #  local-variables-are-used: false
    #  generated-is-used: false

formatters:
  exclusions:
    warn-unused: true
    generated: strict

issues:
  max-issues-per-linter: 1000
  max-same-issues: 100
  fix: true
