version: "3"

vars:
  BINARY_NAME: panix
  BUILD_DIR: ./build
  DIST_DIR: ./dist
  DEBUG_DIR: ./debug

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  run:
    desc: Run the application with go run
    cmds:
      -  go run cmd/main.go {{.CLI_ARGS}}

  run-race:
    desc: Run the application with go run
    env:
      GORACE: log_path={{.DEBUG_DIR}}/race.log
    cmds:
      -  go run --race cmd/main.go {{.CLI_ARGS}}

  run-profile:
    desc: Run the application with go run
    cmds:
      -  go run cmd/main.go --cpuprofile={{.DEBUG_DIR}}/profile.prof {{.CLI_ARGS}}

  profile:
    cmds:
      # https://ksysoev.github.io/posts/go-cpu-profile/
      - go tool pprof -http=:8080 -no_browser {{.DEBUG_DIR}}/profile.prof

  nix:build:
    desc: Build the package using nix
    cmds:
      - nix build path:$(pwd)#default --extra-experimental-features "nix-command flakes" 2>&1

  nix:run:
    desc: Run the application using nix
    cmds:
      - nix run path:$(pwd)#default --extra-experimental-features "nix-command flakes" -- {{.CLI_ARGS}}

  nix:update-hash:
    desc: Update vendorHash after dependency changes
    cmds:
      - nix-prefetch-git --url file://$(pwd) --rev HEAD 2>&1 | jq -r '.sha256'
